### ISSUE TITLE
GFCI does not produce a DAG or PAG or anything graphical

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/r-causal#16]
Howdy, 
GFCI does not produce any sort of graph object. Could this feature be added? I will have to use the tetrad plugin for Cytoscape for this one, I think, for now. 
Thanks!
Scott

**Comment by chirayukong** [comment]
I have a problem to visualize this kind of o--o or o--> or <--o edges in R. Do you have any idea about it?

Kong

**Comment by kingfish777** [comment]
What are the "o" symbols called (and what do they mean [just a refresher])? It has been a long time since Sunday! I would probably do that in igraph with an edge attribute.

**Comment by chirayukong** [comment]
It is one of the PAG attributes indicating that there is a possibility that a latent node (confounder) is between two nodes.

**Comment by kingfish777** [comment]
Nice!!!! That is really cool. In my case, I could return to the literature and attempt to identify some additional confounding variables.

**Comment by kingfish777** [comment]
Do you have any idea what sort of format the cytoscape/tetrad interface expects input to be in? 
Looking at the java, I tried the following:
pain -> medication
medication -> ade
etc.

**Comment by chirayukong** [comment]
I have no idea. You should submit an issue on the cytoscape-tetrad repo.
Jeremy should be able to answer your question.

**Comment by chirayukong** [comment]
Scott, FYI. Credit: Jitske Venema Shunfenthal

To further support you in using our Causal Discovery tools, we have opened the CCD Helpdesk for questions on the use of Tetrad and other CCD tools.
 
The helpdesk will be open from 12:00 noon - 1:00 PM (EST) every weekday and Saturday.
 
To reach us, you can:
1)      Send an email: ccd.user.helpdesk@gmail.com

2)      (Video) Call us:  https://hangouts.google.com/

3)      Chat with us: https://hangouts.google.com/

4)      Share your screen with us:  https://hangouts.google.com/

 
Calling, chatting and screen-sharing work best if you use a Google account and the Chrome browser.
 
If you don't have a Google account, you can't initiate a Hangouts chat session or a call. However, you can email and request that we (CCD Helpdesk) set up a chat or video call using your email address. You will then receive an invitation to join the chat or call. Note: depending on what browser or other software you are using, you may find you need to install Chrome or additional software in order to use Hangouts.
 
Best regards,

ccd.user.helpdesk@gmail.com
